# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: exceedra.product
email: no@email
description: > # this means to ignore newlines until "baseurl:"
  Exceedra product blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://exceedrarandd.cloudapp.net:10117/" # the base hostname & protocol for your site

encoding: utf-8

repository: "/_git/Product%20(Documentation)%20GIT/"
highlighter: rouge

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 1..4

# Plugins
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-paginate

paginate: 3
paginate_path: "/articles/page:num/"

collections:
  guidelines:
    output:       true
    permalink:    /guidelines/:path/
  authors:
    output:       true
    permalink:    /authors/:path/
  releasenotes:
    output:       true
    permalink:    /releasenotes/:path/

defaults:
  - scope:
      path:       ""
      type:       guidelines
    values:
      layout:     guidelines

exclude:
  - archive
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - token
  - bin
