home:        "/"
articles:    "/articles/"
guidelines:  "/guidelines/"
releasenotes:  "/releasenotes/"
logout:        "/logout/"
repository:  "https://exceedrasoftware.visualstudio.com/_git/Product%20(Documentation)%20GIT"
navigation:
  - url:   '/articles/'
    title: 'Articles'
  - url:   '/guidelines/'
    title: 'Guidelines'
  # - url:   '/authors/'
  #   title: 'Authors'
  - url:   '/releasenotes/'
    title: 'Release notes'
  - url: '/'
    title:  ''
  - url:   '/logout/'
    title: 'Logout'
