home:        "/"
articles:    "/articles/"
guidelines:  "/guidelines/"
repository:  "https://exceedrasoftware.visualstudio.com/_git/Product%20(Documentation)%20GIT"
navigation:
  - url:   '/articles/'
    title: 'Articles'
  - url:   '/guidelines/'
    title: 'Guidelines'
  - url:   '/authors/'
    title: 'Authors'
  - url:   '/careers'
    title: 'Work with us!'
